name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # หรือ master ตามชื่อ branch ของคุณ

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Publish
      run: dotnet publish MyMudApp.Client/MyMudApp.Client.csproj -c Release -o release --nologo
    
    - name: Change base-tag in index.html
      run: sed -i 's/<base href="\/" \/>/<base href="\/MyMudApp\/" \/>/g' release/wwwroot/index.html
    
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html
    
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: release/wwwroot
        branch: gh-pages